### PR TITLE
properly correct consts

### PR DESCRIPTION
**Pull request by stevenweber**

### CODE REVIEW

**Review by ebenoist — APPROVED** [review]
Are you going to send this one upstream?

**Comment by stevenweber** [comment]
The author has not made any effort merging the [original PR](https://github.com/aergonaut/rubocop-inclusivity/pull/4), so was planning on just updating the PR branch with these changes as well.

**Comment by ebenoist** [comment]
That's more or less what I figured.

**Comment by ebenoist** [comment]
Merged!

**Pull request merged**
